version: '3'

services:
 codechallenge:
  build: .
  depends_on:
    - db
  ports:
    - "8888:8888"
  volumes:
      - ./:/usr/src/app  

 db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: codechallenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password

 adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db_data:
